name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - autopep8
  - awscli
  - basemap
  - BeautifulSoup4
  - black
  - bokeh
  - cmocean
  - codecov
  - cookiecutter
  - coverage
  - cython 
  - dask
  - dask-jobqueue
  - dask-ml
  - dask-mpi
  - datashader
  - distributed
  - fastparquet
  - flake8
  - gcsfs
  - geopandas 
  - geoviews
  - ghp-import
  - graphviz
  - holoviews
  - hvplot
  - intake
  - intake-cmip
  - intake-xarray
  - invoke
  - ipywidgets
  - isort 
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab
  - lz4
  - Markdown
  - matplotlib
  - metakernel
  - mpi4py
  - mpich
  - nb_conda_kernels
  - nbdime
  - nbserverproxy
  - nbsphinx
  - netcdf4
  - networkx
  - nodejs
  - numba 
  - numcodecs
  - numpy>=1.15.0
  - numpydoc
  - pandas
  - panel
  - pango 
  - papermill
  - pelican
  - pint
  - pyarrow
  - pylint
  - pymc3
  - pytest
  - pytest-cov
  - pytest-cpp
  - pytest-icdiff
  - python-blosc
  - python-graphviz
  - python=3.6
  - pytorch-cpu
  - rasterio
  - recommonmark 
  - s3fs
  - scikit-image
  - scikit-learn>=0.20
  - scikit-plot
  - scipy
  - scrapy
  - seaborn
  - setuptools=39.1.0
  - siphon
  - sphinx
  - sphinx_rtd_theme
  - swig 
  - tqdm 
  - twine
  - typogrify
  - umap-learn
  - unyt 
  - watermark
  - wheel
  - xarray
  - xarray-extras
  - xgboost
  - xo
  - xonsh
  - yt 
  - zarr
  - pip:
     - bash_kernel
     - cfgrib
     - jupyter-repo2docker
     - msgpack-python
     - pre-commit
     - pre-commit-hooks
     - pytest-print
     - sphinx_copybutton
