name: pangeo
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - xarray
  - xonsh
  - xo
  - pandas
  - numpy
  - holoviews
  - geoviews
  - hvplot
  - dask=0.18.2
  - distributed=1.22.0
  - dask-jobqueue
  - mpi4py
  - fastparquet
  - netcdf4
  - jupyterlab
  - jupyter_contrib_nbextensions
  - scipy
  - seaborn
  - matplotlib
  - numba
  - zarr
  - python-graphviz
  - nodejs
  - ipywidgets
  - ipympl
  - widgetsnbextension
  - yt
  - autopep8
  - yapf
  - pytest
  - importnb
  - sympy
  - cython
  - pyarrow
  - scikit-learn
  - python-snappy
  - streamz
  - pyyaml
  - isort
  - datashader
  - phantomjs
  - pip:
      - version-information
