#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter contrib nbextension install --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension \
                             @jupyterlab/toc \
                             jupyter-leaflet 
                             


python -m bash_kernel.install
#EOF
